#-- I/O --#
# file listing samples and associated data
samples_file: tests/samples/samples_n10.txt

## column names in samples table
samples_col: 'ncbi_organism_name'
fasta_file_path_col: 'fasta_file_path'
taxID_col: 'ncbi_species_taxid'    # or 'gtdb_taxid'
taxonomy_col: 'ncbi_taxonomy'      # or 'gtdb_taxonomy'

# output location
output_dir: tests/output_n10/

# temporary file directory (your username will be added automatically)
tmp_dir: /ebio/abt3_scratch/

#-- databases to create --#
# Replace "Create" with "Skip" to skip creation of any of these
# Note that braken relies on the kraken2 database
databases:
  kraken2: Create
  bracken: Create
  humann3_bowtie2: Create
  humann3_diamond: Create
  metaphlan3: Skip #Create
  
# Name for base directory holding all created databases
db_name: UniRef90 #GTDB-custom
# Name of the humann3 diamond database (must match naming allowed by humann3)
dmnd_name: uniref90_201901.dmnd

#-- keep intermediate files required for re-creating DBs (eg., w/ more genomes) --#
# If "True", the intermediate files are saved to `output_dir`
# Else, the intermediate files are temporarily stored in `temp_folder`
use_ancient: True

#-- if custom NCBI taxdump files (or just Skip) --#
# Used for kraken taxonomy
names_dmp: Skip 
nodes_dmp: Skip 

#-- software parameters --#
# `vsearch_per_genome` = per-genome gene clustering
# `vsearch_all` = all genes clustered (including `humann_nuc_seqs` & `humann_prot_seqs`)
# for humann3, use either mmseqs or diamond (both will not be used)
# for humann3::mmseqs_search::run, --num-iterations must be >=2
params:
  ionice: -c 3
  bracken:
    build_kmer: 35
    build_read_lens:
      - 100
      - 150
    keep_intermediate: True 
  genes:
    prodigal: ""
    vsearch_per_genome: --id 0.97 --strand both --qmask none --fasta_width 0
    keep_gene_info: True
    mmseqs_cluster: --min-seq-id 0.9 -c 0.8
    mmseqs_cluster_method: linclust         # or "cluster", which is slower
    keep_cluster_db: True
    keep_annot_genes: True
  humann3:
    batches: 10
    mmseqs_search:
      db: /ebio/abt3_projects/databases_no-backup/mmseqs/UniRef90/UniRef90
      db_index: -s 6
      run: -e 1e-3 --max-accept 1 --max-seqs 100 -s 6 --num-iterations 2
    diamond:
      db: /ebio/abt3_projects/databases_no-backup/humann3/201901/uniref50/uniref50_201901.dmnd
      run: Skip #--evalue 1e-3 --query-cover 80 --id 50 --max-target-seqs 1 --block-size 4 --index-chunks 2
    propagate_annotations: --min-cov 80 --min-pident 0.9
  metaphlan3:
    species_specific_markers: --ext-abs-cutoff 10 --ext-rel-cutoff 0.1

#-- If adding genes to humann database --#
# If you have nucleotide/amino-acid gene sequences formatted for humann,
# provide the file paths to the fasta files below (gzip'ed).
# These will be clustered with the rest of the genes and then annotated like the others.
humann_nuc_seqs: Skip
humann_prot_seqs: Skip

#-- snakemake pipeline --#
pipeline:
  snakemake_folder: ./
  script_folder: ./bin/scripts/
